# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 314f3990619f6685a23e2526df4a5599b38854b0dec44d9d31b712a57c7a13231dd7825b062c0c49b607178ed0769b528479bab5e7fcdc9e9e2038b181c3c5df

test:
  secret_key_base: fe53e5f9eb68403c2417af71ff8a261ae2e59e31f71d0f55c7fcb21ae065a0d9929523d7719a519514622b1acb43f96727fe9d314a1f522ca15844fdc65f9813

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
